services:
   app:
     build: .
     command: python -u main.py
     ports:
       - "5000:5000"
     volumes:
       - .:/app
     links:
       - db
   db:
       image: mongo:latest
       ports:
        - "27017:27017"